#!/usr/bin/env bash
# Function to display DNS information for a specific subdomain
get_dns_info() {
    local domain="$1"
    local subdomain="$2"
    
    if [[ -n "$subdomain" ]]; then
        dig_output=$(dig "$subdomain.$domain" +short)
        record_type=$(dig "$subdomain.$domain" +short | awk 'NR==1{print $1}')
        echo "The subdomain $subdomain is a $record_type record and points to $dig_output"
    else
        subdomains=("www" "lb-01" "web-01" "web-02")
        for sub in "${subdomains[@]}"; do
            dig_output=$(dig "$sub.$domain" +short)
            record_type=$(dig "$sub.$domain" +short | awk 'NR==1{print $1}')
            echo "The subdomain $sub is a $record_type record and points to $dig_output"
        done
    fi
}

# Main script

# Check if domain argument is provided
if [[ $# -lt 1 ]]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

get_dns_info "$domain" "$subdomain"
