#!/usr/bin/env bash
# script must accept 2 arguments: domain and subdomain
#Output:The subdomain is a [RECORD_TYPE] and points to [DESTINATION]

get_dns_inf () {
    get=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $get" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  get_dns_inf "$1" "www"
  get_dns_inf "$1" "lb-01"
  get_dns_inf "$1" "web-01"
  get_dns_inf "$1" "web-02"

elif [ "$#" == 2 ]
then
  get_dns_inf "$1" "$2"
fi
