#!/bin/bash

# Check if the number of arguments is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the arguments to variables
FILE=$1
IP=$2
USERNAME=$3
KEY=$4

# Use scp to transfer the file
scp -i "$KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$IP":~/
