#!/usr/bin/env bash
# Check if less than 4 parameters are passed

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign the parameters to variables
FILE="/ALX/alx-system_engineering-devops/0x0C-web_server/some_page.html"
SERVER_IP="34.239.249.165"
USERNAME="ubuntu"
SSH_KEY="/.ssh/id_rsa"

# Transfer the file using scp with strict host key checking disabled
scp -i "$SSH_KEY" -o StrictHostKeyChecking=no "$FILE" "$USERNAME"@"$SERVER_IP":~/

# Remotely execute the ls ~/ command via ssh to see what ~/ contains
ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "$USERNAME"@"$SERVER_IP" 'ls ~/'

# Remotely execute the ls ~/ command via ssh to see that the file has been successfully transferred
ssh -i "$SSH_KEY" -o StrictHostKeyChecking=no "$USERNAME"@"$SERVER_IP" 'ls ~/' | grep $(basename "$FILE")
