#!/usr/bin/env bash
# Update package index
sudo apt-get -y update

# Install Nginx
sudo apt-get -y install nginx

# Ensure Nginx is listening on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create HTML file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Reload Nginx configuration
sudo nginx -s reload

sudo service nginx start
