#!/usr/bin/env bash
# Define the redirect location block
REDIRECT_BLOCK="location /redirect_me {
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"

# Edit the default Nginx configuration file to add the redirect location block
sudo sed -i "/server_name _;/a \\$REDIRECT_BLOCK" /etc/nginx/sites-available/default

sudo service nginx
