#!/usr/bin/env bash

# Edit the Nginx configuration file
sudo sed -i '/server {/a \
    location /redirect_me { \
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4; \
    } \
' /etc/nginx/sites-available/default

sudo service nginx
