#!/usr/bin/env bash
# Install Nginx
sudo apt update
sudo apt install nginx -y

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Create a configuration file for the custom 404 page
echo 'server {
    listen 80;
    server_name localhost;

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        root /var/www/html;
        internal;
    }
}' | sudo tee /etc/nginx/sites-available/custom_404

# Enable the configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo systemctl restart nginx
