#!/usr/bin/env bash
# Install Nginx
sudo apt update
sudo apt install nginx -y

#redirection of the website
sudo sed -i '/server_name _;/a \	location /redirect_me {\n		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n	}' /etc/nginx/sites-available/default

#custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

#configuring nginx to use custom 404 page
sudo sed -i '/server_name _;/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                internal;\n        }' /etc/nginx/sites-available/default

# Get the hostname of the server
HOSTNAME=$(hostname)

# Create a configuration file for the custom header
echo "server {
    listen 80;
    server_name localhost;

    location / {
        add_header X-Served-By $HOSTNAME;
    }
}" | sudo tee /etc/nginx/sites-available/custom_header

# Enable the configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo systemctl restart nginx
