#!/usr/bin/env bash
# Install Nginx
sudo apt update
sudo apt install nginx -y

# Get the hostname of the server
HOSTNAME=$(hostname)

# Create a configuration file for the custom header
echo "server {
    listen 80;
    server_name localhost;

    location / {
        add_header X-Served-By $HOSTNAME;
    }
}" | sudo tee /etc/nginx/sites-available/custom_header

# Enable the configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Restart Nginx to apply the changes
sudo systemctl restart nginx
