#!/usr/bin/env bash
# Debugging Nginx not listening on port 80
# Create a symbolic link between the two files

# Remove the existing symbolic link if it exists
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Reload Nginx to apply the changes
sudo service nginx reload
