#!/usr/bin/env bash
#debugging nginx to listen to port80
#create a symbolic link

rm /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx start
