#!/usr/bin/env bash
# Change default port to 80, restart Nginx, and kill lingering processes

sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default && \
sudo service nginx restart && \
pkill -o nginx
