#!/usr/bin/env bash
# Function to handle signals

signal_handler() {
    case $1 in
        SIGTERM)
            echo "I hate the kill command"
            rm /var/run/myscript.pid
            exit 0
            ;;
        SIGINT)
            echo "Y U no love me?!"
            ;;
        SIGQUIT)
            rm /var/run/myscript.pid
            exit 0
            ;;
    esac
}


trap 'signal_handler SIGTERM' SIGTERM
trap 'signal_handler SIGINT' SIGINT
trap 'signal_handler SIGQUIT' SIGQUIT


echo $$ > /var/run/myscript.pid
while true; do
    echo "To infinity and beyond"
    sleep 1
done
