#!/usr/bin/env bash

# This script tells a story based on the content of the /etc/passwd file.

# Read the file /etc/passwd line by line
while IFS=':' read -r username userid groupid user_info homedir shell; do
    # Extract additional information from user_info
    passcode=$(echo "$user_info" | cut -d ',' -f 1)
    info=$(echo "$user_info" | cut -d ',' -f 2-)

    # Display the story for each user
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode $passcode, more info about the user here: $info"
done < /etc/passwd
