#!/usr/bin/env bash
# Stop Nginx service if it's running

sudo service nginx stop
sudo pkill apache2

# Modify the main Nginx configuration file to run as the 'nginx' user
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Change the default server configuration to listen on port 8080
sudo sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 default_server;/listen \[::\]:8080 default_server;/' /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Start Nginx service
sudo service nginx start
